/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stock;

import stock.util.PasswordService;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Magency
 */
public class DialogMDP extends javax.swing.JFrame {

    /**
     * Creates new form DialogMDP
     */
    public DialogMDP() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelNomFenetre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelInstr = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        btnValider = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelNomFenetre.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        labelNomFenetre.setForeground(new java.awt.Color(51, 51, 51));
        labelNomFenetre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomFenetre.setText("Gestion de stock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        getContentPane().add(labelNomFenetre, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        labelInstr.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        labelInstr.setText("Entrez le mot de passe pour accéder à l'application :");
        labelInstr.setMinimumSize(new java.awt.Dimension(500, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(labelInstr, gridBagConstraints);

        PasswordField.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        PasswordField.setActionCommand("<Not Set>");
        PasswordField.setMinimumSize(new java.awt.Dimension(100, 28));
        PasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel1.add(PasswordField, gridBagConstraints);

        btnValider.setText("Valider");
        btnValider.setMinimumSize(new java.awt.Dimension(100, 30));
        btnValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel1.add(btnValider, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 50);
        getContentPane().add(jPanel1, gridBagConstraints);

        btnQuitter.setText("Quitter l'application");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        getContentPane().add(btnQuitter, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldKeyPressed
        int key = evt.getKeyCode();
        if (key == java.awt.event.KeyEvent.VK_ENTER)
        {
            verifMDP();
        }
    }//GEN-LAST:event_PasswordFieldKeyPressed

    private void btnValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMouseClicked
        verifMDP();
    }//GEN-LAST:event_btnValiderMouseClicked

    
    private void verifMDP()
    {
        String MDPcourant = "Gk9ruPcbNSrcliGlNy1HvO/5lws=";
        PasswordService ps = new PasswordService();
        try {
            String MDPentré = ps.encrypt(String.valueOf(this.PasswordField.getPassword()));          
            if (MDPentré.equals(MDPcourant))
            {
                stock.menu.FenetreMenuPrincipal fMenuPrincipal = new stock.menu.FenetreMenuPrincipal();
               fMenuPrincipal.setVisible(true);
               this.dispose();
               
            }
            else
            {
                this.PasswordField.setText("");
                
                
            }
            
        } catch (Exception ex) {
            Logger.getLogger(DialogMDP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnValider;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelInstr;
    private javax.swing.JLabel labelNomFenetre;
    // End of variables declaration//GEN-END:variables
}
