/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.menu;

import javax.swing.ImageIcon;
import stock.menu.entrepot.FenetreMenuEntrepot;
import stock.util.connexion.connexion_bdd;
import stock.util.dial.DialogueChoixImport;


/**
 *
 * @author Magency
 */
public class FenetreMenuPrincipal extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form FenetreMenuPrincipal
     */
    
    public FenetreMenuPrincipal() {
        initComponents();
        redimensionnerFenetre();
    }
    
    public FenetreMenuPrincipal(int longueur, int largeur) {
        this();
        this.setSize(new java.awt.Dimension(longueur, largeur));
    }

    ImageIcon imgIconEntrepot;
    ImageIcon imgIconOP;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelNomFenetre = new javax.swing.JLabel();
        btnOp = new javax.swing.JButton();
        btnEntrepot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("MenuPrincipal");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelNomFenetre.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        labelNomFenetre.setForeground(new java.awt.Color(51, 51, 51));
        labelNomFenetre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomFenetre.setText("Gestion de stock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        getContentPane().add(labelNomFenetre, gridBagConstraints);

        btnOp.setBackground(new java.awt.Color(255, 255, 255));
        imgIconOP = new javax.swing.ImageIcon(getClass().getResource("/stock/images/Bouton OP.PNG"));
        btnOp.setIcon(imgIconOP);
        btnOp.setToolTipText("Faire des traitements depuis une OP");
        btnOp.setBorderPainted(false);
        btnOp.setContentAreaFilled(false);
        btnOp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOp.setMaximumSize(new java.awt.Dimension(512, 512));
        btnOp.setPreferredSize(new java.awt.Dimension(370, 370));
        btnOp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        getContentPane().add(btnOp, gridBagConstraints);

        btnEntrepot.setBackground(new java.awt.Color(255, 255, 255));
        imgIconEntrepot = new javax.swing.ImageIcon(getClass().getResource("/stock/images/Bouton Entrepot.PNG"));
        btnEntrepot.setIcon(imgIconEntrepot);
        btnEntrepot.setToolTipText("Faire des traitements depuis l'entrepôt");
        btnEntrepot.setBorderPainted(false);
        btnEntrepot.setContentAreaFilled(false);
        btnEntrepot.setFocusPainted(false);
        btnEntrepot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntrepot.setPreferredSize(new java.awt.Dimension(370, 370));
        btnEntrepot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrepotMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 20);
        getContentPane().add(btnEntrepot, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        redimensionnerFenetre();        
    }//GEN-LAST:event_formComponentResized

    private void btnEntrepotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrepotMouseClicked
        FenetreMenuEntrepot fMenuEntrepot = new FenetreMenuEntrepot(this.getWidth(), this.getHeight());
        fMenuEntrepot.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEntrepotMouseClicked

    private void btnOpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpMouseClicked
        // Faudra mettre la fenetre de choix d'OP en cours
/////////////////////           A FAIRE                 ////////////////////////

        connexion_bdd bdd = new connexion_bdd();

        String dbname = bdd.getlocal().getdatabasename();
        bdd.closeall();

        DialogueChoixImport dChoixImport = new DialogueChoixImport(this, true, 
                                        this.getWidth(), this.getHeight(),
                                    null, dbname, "OPReception");
        dChoixImport.setVisible(true);

    }//GEN-LAST:event_btnOpMouseClicked

    private void redimensionnerFenetre()
    {
        java.awt.Image imgEntrepot = imgIconEntrepot.getImage();
        int dim = Math.min(btnEntrepot.getWidth(), btnEntrepot.getHeight());
        java.awt.Image newImgEntrepot = imgEntrepot.getScaledInstance(dim, dim, java.awt.Image.SCALE_DEFAULT);
        btnEntrepot.setIcon(new javax.swing.ImageIcon(newImgEntrepot));

        java.awt.Image imgOP = imgIconOP.getImage();
        java.awt.Image newImgOP = imgOP.getScaledInstance(dim, dim, java.awt.Image.SCALE_DEFAULT);
        btnOp.setIcon(new javax.swing.ImageIcon(newImgOP));

        labelNomFenetre.setFont(labelNomFenetre.getFont().deriveFont(labelNomFenetre.getHeight()));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrepot;
    private javax.swing.JButton btnOp;
    private javax.swing.JLabel labelNomFenetre;
    // End of variables declaration//GEN-END:variables
}
