/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.menu.entrepot;


import stock.util.dial.DialogueChoixOP;
import javax.swing.ImageIcon;
import stock.menu.FenetreMenuPrincipal;
import stock.menu.entrepot.list.FenetreEntrepotListeiPads;
import stock.menu.entrepot.list.FenetreEntrepotListesErveurs;
import stock.menu.entrepot.planning.FenetreEntrepotPlanning;

/**
 *
 * @author Magency
 */
public class FenetreMenuEntrepot extends javax.swing.JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ImageIcon imgIconEnvoi;
    private ImageIcon imgIconListe;
    private ImageIcon imgIconReception;
    private ImageIcon imgIconPlanning;
    
    //Ajouter by me
  private ImageIcon imgIconListeServeur;

    /**
     * Creates new form FenetreMenuPrincipal
     */
    public FenetreMenuEntrepot() {
        initComponents();
        redimensionnerFenetre();
    }
    
    public FenetreMenuEntrepot(int longueur, int largeur) {
        initComponents();
        this.setSize(new java.awt.Dimension(longueur, largeur));
        redimensionnerFenetre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnRetour = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        labelNomFenetre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnListe = new javax.swing.JButton();
        btnPlanning = new javax.swing.JButton();
        btnEnvoi = new javax.swing.JButton();
        btnReception = new javax.swing.JButton();
        btnServeur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("MenuPrincipal");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        btnRetour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/images/Bouton Retour.png"))); // NOI18N
        btnRetour.setToolTipText("Retour");
        btnRetour.setBorderPainted(false);
        btnRetour.setContentAreaFilled(false);
        btnRetour.setMaximumSize(new java.awt.Dimension(32, 32));
        btnRetour.setMinimumSize(new java.awt.Dimension(32, 32));
        btnRetour.setPreferredSize(new java.awt.Dimension(32, 32));
        btnRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetourMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(btnRetour, gridBagConstraints);

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/images/Bouton Home.PNG"))); // NOI18N
        btnHome.setToolTipText("Menu principal");
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setMaximumSize(new java.awt.Dimension(32, 32));
        btnHome.setMinimumSize(new java.awt.Dimension(32, 32));
        btnHome.setPreferredSize(new java.awt.Dimension(32, 32));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(btnHome, gridBagConstraints);

        labelNomFenetre.setFont(new java.awt.Font("Lucida Grande", 1, 48)); // NOI18N
        labelNomFenetre.setForeground(new java.awt.Color(51, 51, 51));
        labelNomFenetre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomFenetre.setText("Entrepôt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        getContentPane().add(labelNomFenetre, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnListe.setBackground(new java.awt.Color(255, 255, 255));
        imgIconListe = new javax.swing.ImageIcon(getClass().getResource("/stock/images/Bouton Liste.PNG"));
        btnListe.setIcon(imgIconListe);
        btnListe.setToolTipText("Liste de tous les iPads");
        btnListe.setBorderPainted(false);
        btnListe.setContentAreaFilled(false);
        btnListe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListe.setMinimumSize(new java.awt.Dimension(64, 64));
        btnListe.setPreferredSize(new java.awt.Dimension(64, 64));
        btnListe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListeMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        jPanel1.add(btnListe, gridBagConstraints);
        
        
        //Ajout by Reyana
        
        btnServeur.setBackground(new java.awt.Color(255, 255, 255));
        imgIconListeServeur = new javax.swing.ImageIcon(getClass().getResource("/stock/images/Bouton Serveur.PNG"));
        btnServeur.setIcon(imgIconListeServeur);
        btnServeur.setToolTipText("Liste de tous les serveurs");
        btnServeur.setBorderPainted(false);
        btnServeur.setContentAreaFilled(false);
        btnServeur.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnServeur.setMinimumSize(new java.awt.Dimension(128, 128));
        btnServeur.setPreferredSize(new java.awt.Dimension(128, 128));
        btnServeur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServeurMouseClicked(evt);
            }
        });
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        jPanel1.add(btnServeur, gridBagConstraints);

        btnPlanning.setBackground(new java.awt.Color(255, 255, 255));
        imgIconPlanning = new javax.swing.ImageIcon(getClass().getResource("/stock/images/Bouton Planning.PNG"));
        btnPlanning.setIcon(imgIconPlanning);
        btnPlanning.setToolTipText("Plannification des operations, visualisation du nombre d'iPads disponibles sur une periode");
        btnPlanning.setBorderPainted(false);
        btnPlanning.setContentAreaFilled(false);
        btnPlanning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlanning.setMinimumSize(new java.awt.Dimension(64, 64));
        btnPlanning.setPreferredSize(new java.awt.Dimension(64, 64));
        btnPlanning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlanningMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        jPanel1.add(btnPlanning, gridBagConstraints);

        btnEnvoi.setBackground(new java.awt.Color(255, 255, 255));
        imgIconEnvoi = new javax.swing.ImageIcon(getClass().getResource("/stock/images/Bouton Envoi.PNG"));
        btnEnvoi.setIcon(imgIconEnvoi);
        btnEnvoi.setToolTipText("Envoi d'iPads vers une OP");
        btnEnvoi.setBorderPainted(false);
        btnEnvoi.setContentAreaFilled(false);
        btnEnvoi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnvoi.setMinimumSize(new java.awt.Dimension(64, 64));
        btnEnvoi.setPreferredSize(new java.awt.Dimension(64, 64));
        btnEnvoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnvoiMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        jPanel1.add(btnEnvoi, gridBagConstraints);

        btnReception.setBackground(new java.awt.Color(255, 255, 255));
        imgIconReception = new javax.swing.ImageIcon(getClass().getResource("/stock/images/Bouton Reception.PNG"));
        btnReception.setIcon(imgIconReception);
        btnReception.setToolTipText("Reception d'iPads revenant d'une OP");
        btnReception.setBorderPainted(false);
        btnReception.setContentAreaFilled(false);
        btnReception.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReception.setMinimumSize(new java.awt.Dimension(64, 64));
        btnReception.setPreferredSize(new java.awt.Dimension(64, 64));
        btnReception.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReceptionMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 20, 20);
        jPanel1.add(btnReception, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        redimensionnerFenetre();
    }//GEN-LAST:event_formComponentResized

    private void btnRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetourMouseClicked
        FenetreMenuPrincipal fMenuPrincipal = new FenetreMenuPrincipal(this.getWidth(), this.getHeight());
        fMenuPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRetourMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        this.dispose();
        FenetreMenuPrincipal fMenuPrincipal = new FenetreMenuPrincipal(this.getWidth(), this.getHeight());
        fMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnListeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListeMouseClicked
        FenetreEntrepotListeiPads fEntrepotListe = new FenetreEntrepotListeiPads(this.getWidth(), this.getHeight());
        fEntrepotListe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListeMouseClicked

    
    private void btnServeurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServeurMouseClicked
        FenetreEntrepotListesErveurs fEntrepotServeur = new FenetreEntrepotListesErveurs(this.getWidth(), this.getHeight());
        fEntrepotServeur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnServeurMouseClicked
    
    private void btnPlanningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlanningMouseClicked
        FenetreEntrepotPlanning fEntrepotPlanning = new FenetreEntrepotPlanning(this.getWidth(), this.getHeight());
        fEntrepotPlanning.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPlanningMouseClicked

    private void btnEnvoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnvoiMouseClicked
        DialogueChoixOP dChoixOP = new DialogueChoixOP("entrepotEnvoi",this, true, this.getWidth(), this.getHeight());
        dChoixOP.setVisible(true);
    }//GEN-LAST:event_btnEnvoiMouseClicked

    private void btnReceptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReceptionMouseClicked

        DialogueChoixOP dChoixOP = new DialogueChoixOP("entrepotReception",this, true, this.getWidth(), this.getHeight());
        dChoixOP.setVisible(true);        
                
    }//GEN-LAST:event_btnReceptionMouseClicked

    /**
    * @brief Redimensionne la taille des images des boutons selon la taille de la fenêtre
    */
    private void redimensionnerFenetre()
    {
        java.awt.Image imgListe = imgIconListe.getImage();
        int dim = Math.min(btnListe.getWidth(), btnListe.getHeight());
        java.awt.Image newImgListe = imgListe.getScaledInstance(dim, dim, java.awt.Image.SCALE_DEFAULT);
        btnListe.setIcon(new javax.swing.ImageIcon(newImgListe));
        
        java.awt.Image imgPlanning = imgIconPlanning.getImage();
        java.awt.Image newImgPlanning = imgPlanning.getScaledInstance(dim, dim, java.awt.Image.SCALE_DEFAULT);
        btnPlanning.setIcon(new javax.swing.ImageIcon(newImgPlanning));

        java.awt.Image imgEnvoi = imgIconEnvoi.getImage();
        java.awt.Image newImgEnvoi = imgEnvoi.getScaledInstance(dim, dim, java.awt.Image.SCALE_DEFAULT);
        btnEnvoi.setIcon(new javax.swing.ImageIcon(newImgEnvoi));
        
        java.awt.Image imgReception = imgIconReception.getImage();
        java.awt.Image newImgReception = imgReception.getScaledInstance(dim, dim, java.awt.Image.SCALE_DEFAULT);
        btnReception.setIcon(new javax.swing.ImageIcon(newImgReception));
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnvoi;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnListe;
    private javax.swing.JButton btnPlanning;
    private javax.swing.JButton btnReception;
    private javax.swing.JButton btnServeur;

    private javax.swing.JButton btnRetour;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelNomFenetre;
    // End of variables declaration//GEN-END:variables
}
