/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.menu.op.retour;


import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import stock.base.Ipad;

/**
 *
 * @author Magency
 */
public class DialogueListeIpads extends javax.swing.JDialog {
    private FenetreOPRetour fenMere;
    private List<Ipad> listIpadLocale = new ArrayList<Ipad>();
    
    /**
     * Creates new form NewJDialog
     */
    public DialogueListeIpads(java.awt.Frame parent, boolean modal, String title, 
                                                List<Ipad> listIpad) {
        super(parent, modal);
        initComponents();
        // Place le fenetre au centre de la fenetre parent
        this.setLocationRelativeTo(parent);
        
        this.fenMere = (FenetreOPRetour) parent;
        this.listIpadLocale = listIpad;
        
        //Change le titre de la fenetre
        this.labelNomFenetre.setText(title);
        
        // Affichage de chaque iPad de la liste
        int i;
        for (i = 0; i < listIpad.size(); i++)
        {
            afficheIpad(listIpad.get(i));
        }
    }
    
    public DialogueListeIpads(java.awt.Frame parent, boolean modal, int longueur, int largeur, 
                                                    String title, List<Ipad> listIpad) {
        this(parent, modal, title, listIpad);
        this.setSize(new java.awt.Dimension(longueur / 2, largeur / 2));
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelNord = new javax.swing.JPanel();
        labelNomFenetre = new javax.swing.JLabel();
        panelCentre = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        tabIpads = new javax.swing.JTable();
        panelBouton = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Liste des iPads");
        setMinimumSize(new java.awt.Dimension(400, 300));

        panelNord.setLayout(new java.awt.BorderLayout());

        labelNomFenetre.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelNomFenetre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomFenetre.setText("_");
        panelNord.add(labelNomFenetre, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelNord, java.awt.BorderLayout.NORTH);

        panelCentre.setLayout(new java.awt.GridBagLayout());

        jScrollPane.setMinimumSize(new java.awt.Dimension(512, 512));

        tabIpads.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tabIpads.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro de série", "UDID", "Code RFID", "Etiquette"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabIpads.setAutoCreateRowSorter(true);
        tabIpads.setGridColor(new java.awt.Color(102, 102, 102));
        tabIpads.setRowHeight(30);
        tabIpads.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tabIpads.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane.setViewportView(tabIpads);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelCentre.add(jScrollPane, gridBagConstraints);

        getContentPane().add(panelCentre, java.awt.BorderLayout.CENTER);

        btnOK.setText("OK");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOKMouseClicked(evt);
            }
        });
        panelBouton.add(btnOK);

        getContentPane().add(panelBouton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnOKMouseClicked
    
    

    /**
     * @brief Affiche dans la JTable de la fenetre l'iPad passe en parametre (place en fin de liste)
     * 
     * @param iPad iPad a ajouter dans la liste d'affichage
     */
    private void afficheIpad(Ipad iPad)
    {
        // Recupere le modele pour ajouter de nouvelles lignes
        DefaultTableModel dtm = (DefaultTableModel)this.tabIpads.getModel();
        
        // Mise en vecteur des infos des iPads de la liste
        Vector row = new Vector();  
        row.add(iPad.getNumSerie());
        row.add(iPad.getUdid());
        row.add(iPad.getRfid());
        row.add(iPad.getEtiquette());
        
        // Ajout d'une nouvelle ligne avec les donnees de l'iPad ci-dessus
        dtm.addRow(row);
        dtm.fireTableRowsInserted(dtm.getRowCount() - 1, dtm.getRowCount() - 1);
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel labelNomFenetre;
    private javax.swing.JPanel panelBouton;
    private javax.swing.JPanel panelCentre;
    private javax.swing.JPanel panelNord;
    private javax.swing.JTable tabIpads;
    // End of variables declaration//GEN-END:variables
}
