/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.menu.entrepot.list;

import stock.base.Ipad;
import stock.util.connexion.connexion_bdd;
import stock.util.sql.SQL_function;

/**
 *
 * @author Magency
 */
public class DialogueSupprIpad extends javax.swing.JDialog {

    private final FenetreEntrepotListeiPads fenMere;
    private int id;

    /**
     * Creates new form NewJDialog
     */
    public DialogueSupprIpad(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        // Place le fenetre au centre de la fenetre parent
        this.setLocationRelativeTo(parent);
        
        this.fenMere = (FenetreEntrepotListeiPads) parent;
        this.id = id;
        afficheChampsIpad();
    }

    public DialogueSupprIpad(java.awt.Frame parent, boolean modal, int longueur, int largeur, int id) {
        this(parent, modal, id);
        this.setSize(new java.awt.Dimension(longueur / 2, largeur / 2));
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelNomFenetre = new javax.swing.JLabel();
        panelCentre = new javax.swing.JPanel();
        panelPhrase = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelNumBDD = new javax.swing.JLabel();
        labelSN = new javax.swing.JLabel();
        labelEtiquette = new javax.swing.JLabel();
        labelDateAchat = new javax.swing.JLabel();
        labelDateAchat1 = new javax.swing.JLabel();
        txtNumBDD = new javax.swing.JLabel();
        txtSN = new javax.swing.JLabel();
        txtEtiquette = new javax.swing.JLabel();
        txtDateAchat = new javax.swing.JLabel();
        txtDureeGarantie = new javax.swing.JLabel();
        panelUdid = new javax.swing.JPanel();
        labelUdid = new javax.swing.JLabel();
        txtUdid = new javax.swing.JLabel();
        panelBoutons = new javax.swing.JPanel();
        btnRetour = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifier un iPad");
        setMinimumSize(new java.awt.Dimension(400, 300));

        labelNomFenetre.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelNomFenetre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomFenetre.setText("Supprimer un iPad");
        getContentPane().add(labelNomFenetre, java.awt.BorderLayout.NORTH);

        panelCentre.setLayout(new java.awt.GridBagLayout());

        panelPhrase.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Êtes-vous sûrs de vouloir retirer cet iPad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelPhrase.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel8.setText("définitivement de la base de données?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelPhrase.add(jLabel8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelCentre.add(panelPhrase, gridBagConstraints);

        labelNumBDD.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelNumBDD.setText("Numéro dans la BDD : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        panelCentre.add(labelNumBDD, gridBagConstraints);

        labelSN.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelSN.setText("Numéro de série :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        panelCentre.add(labelSN, gridBagConstraints);

        labelEtiquette.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelEtiquette.setText("Etiquette :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        panelCentre.add(labelEtiquette, gridBagConstraints);

        labelDateAchat.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelDateAchat.setText("Date d'achat :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        panelCentre.add(labelDateAchat, gridBagConstraints);

        labelDateAchat1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelDateAchat1.setText("Durée garantie :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        panelCentre.add(labelDateAchat1, gridBagConstraints);

        txtNumBDD.setText("NumDB");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCentre.add(txtNumBDD, gridBagConstraints);

        txtSN.setText("SN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCentre.add(txtSN, gridBagConstraints);

        txtEtiquette.setText("etiquette");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCentre.add(txtEtiquette, gridBagConstraints);

        txtDateAchat.setText("date achat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCentre.add(txtDateAchat, gridBagConstraints);

        txtDureeGarantie.setText("duree");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCentre.add(txtDureeGarantie, gridBagConstraints);

        panelUdid.setLayout(new java.awt.GridBagLayout());

        labelUdid.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelUdid.setText("UDID :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelUdid.add(labelUdid, gridBagConstraints);

        txtUdid.setText("udid");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 1.0;
        panelUdid.add(txtUdid, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelCentre.add(panelUdid, gridBagConstraints);

        getContentPane().add(panelCentre, java.awt.BorderLayout.CENTER);

        btnRetour.setText("Retour");
        btnRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetourMouseClicked(evt);
            }
        });
        panelBoutons.add(btnRetour);

        btnOK.setText("OK");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOKMouseClicked(evt);
            }
        });
        panelBoutons.add(btnOK);

        getContentPane().add(panelBoutons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetourMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnRetourMouseClicked

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
        // Suppression dans la BDD de l'iPad selectionne
        connexion_bdd bdd = new connexion_bdd();
        SQL_function.removeIpadBDD(bdd.getserver().getstatement(), this.id);
        bdd.closeall();
        
        // Actualisation de la JTable
        this.fenMere.refreshJTable(); 
        
    }//GEN-LAST:event_btnOKMouseClicked

    /**
     * @brief Affiche dans chaque champ de la boite de dialogue les informations
     * de l'iPad passe en arametre
     *
     * @param iPad {@link Ipad} dont les informations sont recuperees
     */
    private void afficheChampsIpad()
    {
        int i = 0;
        //Charger la liste d'Ipad depuis la BDD
        connexion_bdd bdd = new connexion_bdd();
        Ipad iPadBDD = SQL_function.getIpadFromId_BDD(bdd.getserver().getstatement(), this.id);          
        if(iPadBDD != null)            
        {           
            this.txtNumBDD.setText(String.valueOf(iPadBDD.getDbNum()));
            this.txtSN.setText(iPadBDD.getNumSerie());
            this.txtUdid.setText(iPadBDD.getUdid());
            this.txtEtiquette.setText(iPadBDD.getEtiquette());
            this.txtDateAchat.setText(iPadBDD.getStringDateAchat());
            this.txtDureeGarantie.setText(iPadBDD.getDureeGarantie());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRetour;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel labelDateAchat;
    private javax.swing.JLabel labelDateAchat1;
    private javax.swing.JLabel labelEtiquette;
    private javax.swing.JLabel labelNomFenetre;
    private javax.swing.JLabel labelNumBDD;
    private javax.swing.JLabel labelSN;
    private javax.swing.JLabel labelUdid;
    private javax.swing.JPanel panelBoutons;
    private javax.swing.JPanel panelCentre;
    private javax.swing.JPanel panelPhrase;
    private javax.swing.JPanel panelUdid;
    private javax.swing.JLabel txtDateAchat;
    private javax.swing.JLabel txtDureeGarantie;
    private javax.swing.JLabel txtEtiquette;
    private javax.swing.JLabel txtNumBDD;
    private javax.swing.JLabel txtSN;
    private javax.swing.JLabel txtUdid;
    // End of variables declaration//GEN-END:variables
}
