/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stock.menu.entrepot.list;

import stock.util.dial.DialogueAvertissement;
import java.text.SimpleDateFormat;
import java.util.Date;
import stock.util.Gestion_Duree_Garantie;
import stock.base.Ipad;
import stock.util.sql.InstructionSql;

/**
 *
 * @author Magency
 */
public class DialogueAjoutIpad extends javax.swing.JDialog {

    private final FenetreEntrepotListeiPads fenMere;
    private boolean isNumSerieOK = false;
    private boolean isUdidOK = false;
    private boolean isRfidOK = false;
    private boolean isEtiquetteOK = false;

    /**
     * Creates new form NewJDialog
     */
    public DialogueAjoutIpad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Place le fenetre au centre de la fenetre parent
        this.setLocationRelativeTo(parent);
        this.fenMere = (FenetreEntrepotListeiPads) parent;
    }

    public DialogueAjoutIpad(java.awt.Frame parent, boolean modal, int longueur, int largeur) {
        this(parent, modal);
        this.setSize(new java.awt.Dimension(longueur / 2, largeur / 2));
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelNomFenetre = new javax.swing.JLabel();
        panelCentre = new javax.swing.JPanel();
        labelSN = new javax.swing.JLabel();
        txtSN = new javax.swing.JTextField();
        panelUdid = new javax.swing.JPanel();
        labelUdid = new javax.swing.JLabel();
        txtUdid = new javax.swing.JTextField();
        labelRfid = new javax.swing.JLabel();
        txtRfid = new javax.swing.JTextField();
        labelEtiquette = new javax.swing.JLabel();
        txtEtiquette = new javax.swing.JTextField();
        labelDateAchat = new javax.swing.JLabel();
        txtDureeGarantie = new javax.swing.JTextField();
        labelDateAchat1 = new javax.swing.JLabel();
        dtAchat = new com.toedter.calendar.JDateChooser();
        panelBoutons = new javax.swing.JPanel();
        btnRetour = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajout d'un iPad");
        setMinimumSize(new java.awt.Dimension(400, 300));

        labelNomFenetre.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        labelNomFenetre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNomFenetre.setText("Ajout d'un iPad");
        getContentPane().add(labelNomFenetre, java.awt.BorderLayout.NORTH);

        java.awt.GridBagLayout panelCentreLayout = new java.awt.GridBagLayout();
        panelCentreLayout.columnWidths = new int[] {0, 0, 0};
        panelCentreLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        panelCentre.setLayout(panelCentreLayout);

        labelSN.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelSN.setText("Numéro de série :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelCentre.add(labelSN, gridBagConstraints);

        txtSN.setPreferredSize(new java.awt.Dimension(100, 28));
        txtSN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSNKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCentre.add(txtSN, gridBagConstraints);

        panelUdid.setLayout(new java.awt.GridBagLayout());

        labelUdid.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelUdid.setText("UDID :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelUdid.add(labelUdid, gridBagConstraints);

        txtUdid.setPreferredSize(new java.awt.Dimension(100, 28));
        txtUdid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUdidKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        panelUdid.add(txtUdid, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelCentre.add(panelUdid, gridBagConstraints);

        labelRfid.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelRfid.setText("RFID :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelCentre.add(labelRfid, gridBagConstraints);

        txtRfid.setPreferredSize(new java.awt.Dimension(100, 28));
        txtRfid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRfidKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCentre.add(txtRfid, gridBagConstraints);

        labelEtiquette.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelEtiquette.setText("Etiquette :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelCentre.add(labelEtiquette, gridBagConstraints);

        txtEtiquette.setPreferredSize(new java.awt.Dimension(100, 28));
        txtEtiquette.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEtiquetteKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCentre.add(txtEtiquette, gridBagConstraints);

        labelDateAchat.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelDateAchat.setText("Date d'achat :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelCentre.add(labelDateAchat, gridBagConstraints);

        txtDureeGarantie.setText("1 an ");
        txtDureeGarantie.setPreferredSize(new java.awt.Dimension(100, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCentre.add(txtDureeGarantie, gridBagConstraints);

        labelDateAchat1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        labelDateAchat1.setText("Durée garantie :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelCentre.add(labelDateAchat1, gridBagConstraints);

        dtAchat.setDate(java.util.Calendar.getInstance().getTime());
        dtAchat.setDateFormatString("dd/MM/yy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        panelCentre.add(dtAchat, gridBagConstraints);

        getContentPane().add(panelCentre, java.awt.BorderLayout.CENTER);

        btnRetour.setText("Retour");
        btnRetour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetourMouseClicked(evt);
            }
        });
        panelBoutons.add(btnRetour);

        btnOK.setText("OK");
        btnOK.setEnabled(false);
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOKMouseClicked(evt);
            }
        });
        panelBoutons.add(btnOK);

        getContentPane().add(panelBoutons, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetourMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnRetourMouseClicked

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
        if (this.btnOK.isEnabled()) {
            String donnee;
            String numSerie = this.txtSN.getText();
            String udid = this.txtUdid.getText();
            String rfid = this.txtRfid.getText();
            String etiquette = this.txtEtiquette.getText();
            Date dateAchat = this.dtAchat.getDate();
            String dureeGarantie = this.txtDureeGarantie.getText();

            //System.out.println(numSerie + "\n" + udid + "\n" + rfid + "\n" + etiquette + "\n" + dateAchat + "\n" + dureeGarantie + "\n");
            // Champs obligatoires
            if (!numSerie.equals("") && !udid.equals("") && !rfid.equals("")) {
                Ipad newIpad = new Ipad(numSerie, udid, rfid);
                // Ajout de l'etiquette si il y en a une
                if (!numSerie.equals("")) {
                    newIpad.setEtiquette(etiquette);
                }

                //Ajout de la date d'achat s'il y en a une correcte
                if (dateAchat != null) {
                    newIpad.setDateAchat(dateAchat);
                }

                // Ajout de la durée de garantie s'il y en a une, 1 an par defaut
                if (!dureeGarantie.equals("")) {
                    newIpad.setDureeGarantie(dureeGarantie);
                } else {
                    newIpad.setDureeGarantie("1 an");
                }
                
                Gestion_Duree_Garantie rgx = new Gestion_Duree_Garantie(); 
                int garantie = rgx.regex(dureeGarantie);
                if (garantie < 0){
                    DialogueAvertissement warning = new DialogueAvertissement(this, true);
                    warning.setVisible(true);
                    //this.dispose();
                }else{
                String date = (dateAchat == null ? "" : new SimpleDateFormat("yy/MM/dd").format(dateAchat));
                donnee = numSerie + "+" + udid + "+" + rfid + "+" + etiquette + "+" + date + "+" + garantie + "+";
                // Ajout du nouvel iPad dans la BDD
                System.out.println(garantie);
                InstructionSql ajout_ipad = new InstructionSql();
                ajout_ipad.Ajout_Ipad(donnee);
                //FenetreEntrepotListeiPads listeIpad = new FenetreEntrepotListeiPads();
                //listeIpad.reinitAffichage();
                //Affichage du nouvel iPad dans la JTable
                this.fenMere.addIpad(newIpad);

                //Suppression de la fenetre
                this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btnOKMouseClicked

    private void txtSNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSNKeyReleased
        // Numero de serie : 11 ou 12 caracteres
        if (this.txtSN.getText().length() == 11 || this.txtSN.getText().length() == 12) {
            this.isNumSerieOK = true;
        } else {
            this.isNumSerieOK = false;
        }
        checkActivationOK();
    }//GEN-LAST:event_txtSNKeyReleased

    private void txtUdidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUdidKeyReleased
        // Udid : 40 caracteres
        if (this.txtUdid.getText().length() == 40) {
            this.isUdidOK = true;
        } else {
            this.isUdidOK = false;
        }
        checkActivationOK();
    }//GEN-LAST:event_txtUdidKeyReleased

    private void txtRfidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRfidKeyReleased
        if (this.txtRfid.getText().length() == 28) {
            this.isRfidOK = true;
        } else {
            this.isRfidOK = false;
        }
        checkActivationOK();
    }//GEN-LAST:event_txtRfidKeyReleased

    private void txtEtiquetteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEtiquetteKeyReleased
        if (!this.txtEtiquette.getText().equals("") && (this.txtEtiquette.getText().length() <= 10)) {
            this.isEtiquetteOK = true;
        }

        if (this.txtEtiquette.getText().equals("")) {
            this.isEtiquetteOK = true;
        }
        checkActivationOK();
    }//GEN-LAST:event_txtEtiquetteKeyReleased

    /**
     * @brief Actives le bouton OK si les champs obligatoires sont remplis
     */
    private void checkActivationOK() {
        //System.out.println(String.valueOf(isNumSerieOK) + String.valueOf(isUdidOK) + String.valueOf(isRfidOK));
        if (this.isNumSerieOK && this.isRfidOK && this.isUdidOK && this.isEtiquetteOK) {
            this.btnOK.setEnabled(true);
        } else {
            this.btnOK.setEnabled(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnRetour;
    private com.toedter.calendar.JDateChooser dtAchat;
    private javax.swing.JLabel labelDateAchat;
    private javax.swing.JLabel labelDateAchat1;
    private javax.swing.JLabel labelEtiquette;
    private javax.swing.JLabel labelNomFenetre;
    private javax.swing.JLabel labelRfid;
    private javax.swing.JLabel labelSN;
    private javax.swing.JLabel labelUdid;
    private javax.swing.JPanel panelBoutons;
    private javax.swing.JPanel panelCentre;
    private javax.swing.JPanel panelUdid;
    private javax.swing.JTextField txtDureeGarantie;
    private javax.swing.JTextField txtEtiquette;
    private javax.swing.JTextField txtRfid;
    private javax.swing.JTextField txtSN;
    private javax.swing.JTextField txtUdid;
    // End of variables declaration//GEN-END:variables
}
